# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qa
  name: easy-gray-gateway-api
  labels:
    app: easy-gray-gateway-api
    release: easy-gray-gateway-api
    podEnv: pod-env
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  selector:
    matchLabels:
      app: easy-gray-gateway-api
      release: easy-gray-gateway-api
  template:
    metadata:
      labels:
        app: easy-gray-gateway-api
        release: easy-gray-gateway-api
    spec:
      imagePullSecrets:
        - name: ali-docker-repository
      containers:
        - name: easy-gray-gateway-api
          image: registry.cn-hangzhou.aliyuncs.com/ranmo/easy-gray-gateway-api:build_number
          command:
            - sh
            - -c
            - (sh /usr/local/app/run.sh)
          env:
            - name: JAVA_OPTS
              value: -Xms1024m -Xmx1024m
            - name: env
              value: pod-env
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: APP_NAME
              value: easy-gray-gateway-api
          envFrom:
            []
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 10080
              protocol: TCP
          resources:
            limits:
              cpu: 1024m
              memory: 1024Mi
            requests:
              cpu: 1024m
              memory: 1024Mi


